name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run Lint
        run: npm run lint
  format:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run Format Check
        run: npm run format:check
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run Build
        run: npm run build
